version: '3.3'

volumes:
  postgres_data:
  static:
  media:

services:
  db:
    container_name: foodgram-db
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    container_name: foodgram-back
    build: ../backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - static:/app/result_build/
  nginx:
    container_name: foodgram-proxy
    build: .
    ports:
      - "80:80"
    volumes:
      - static:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/build/api/docs/
      - media:/media
