# Generated by Django 5.1.4 on 2025-01-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipe_cart_remove_recipe_favourite_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=1, upload_to='recipes/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
